### ISSUE TITLE
Question: Are there plans to have this library do compression and decompression using Zstandard/zstd? 

### ISSUE THREAD

**Issue by jdrews** [101arrowz/fzstd#3]
I noticed this library focuses entirely on decompression while fflate does compression and decompression. Are there plans to enable compression in the future for this library? Thanks!

**Comment by 101arrowz** [comment]
This project was more of an experiment than `fflate`, and I don't really have as thorough an understanding of the Zstandard architecture (especially finite state entropy compression) as I do of DEFLATE. I'm planning to do some more reading on FSE to see if I can implement it effectively.

There's still another concern if I do learn how FSE works. Right now `fzstd` has a real use case for situations where there's only a couple kB to MB of data (i.e. too little for WASM to have a big advantage) or there's a massive amount of data (where the easier data streaming features of `fzstd` make it much more appealing). However, when it comes to compression, I don't know if `fzstd` will be even nearly as  fast as a WASM port, let alone as effective at compression.

For now I don't have any plans to implement a *good* compressor but I'll try to make a working compressor at some point, depending on how difficult FSE is.

**Comment by jdrews** [comment]
Thanks for the vision on the repo!

**Comment by kingdudely** [comment]
Pls Bro I need this speed
