### ISSUE TITLE
Importing this from node fails

### ISSUE THREAD

**Issue by Gozala** [101arrowz/fzstd#5]
I get following errors in node v16.13.0 when importing this

```
(node:18561) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)

./node_modules/fzstd/esm/index.js:40
export var ZstdErrorCode = {
```

As far as I can tell node does not like `export` because `"type": "module"` is not set in package.json so it treats it as cjs instead.

**Comment by 101arrowz** [comment]
I can fix this by changing the extension to `.mjs` for the exported ESM files. I'll do that when I get a chance.
